version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minioCareerOS
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console (web UI)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: careeros-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - minio

volumes:
  minio_data: