spring:
  application:
    name: Placement-Portal

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:6000/testDB}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 0.3

jwt:
  secret-key: ${JWT_SECRET:dhewbd3wyuiuydauwdghjswxgzvjsbckhweiyq3gwifeauhcwgxsjc jd}
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads/resumes}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: ${PORT:8080}